cluster.name: es-cluster 
node.name: es_node_2
network.host: 127.0.0.1
http.port: 9201
transport.tcp.port: 9301
node.master: true
node.data: true
discovery.zen.ping.unicast.hosts: ["127.0.0.1:9300","127.0.0.1:9301"]
cluster.initial_master_nodes: ["127.0.0.1:9300"]
node.ingest: true
node.max_local_storage_nodes: 2
path.data: D:\o99o\Elasticsearch\elasticsearch-7.1.1_cluster_node2\data
path.logs: D:\o99o\Elasticsearch\elasticsearch-7.1.1_cluster_node2\logs
http.cors.enabled: true
http.cors.allow-origin: "*"
#允许跨域访问头部信息
http.cors.allow-headers: "X-Requested-With,Content-Type, Content-Length, Authorization"
xpack.ml.enabled: false
